options:
  title: '## Change Log'
  style: gh-release
  # group names
  names: [New, Fixed, Feature, Update]
  repoUrl: https://github.com/gookit/gitwrap

filters:
  # message length should >= 12
  - name: msgLen
    minLen: 12
  # message words should >= 3
  - name: wordsLen
    minLen: 3
  - name: keywords
    keywords: ['format code']
    exclude: true

# group match rules
# not matched will use 'Other' group.
rules:
  - name: Fixed
    startWiths: [fix]
    contains: ['fix:']
  - name: Feature
    startWiths: [feat, new]
    contains: [feature]
  - name: Update
    startWiths: [update, 'up:']
    contains: [' update']
