title: '## Change Log'
style: gh-release
# group names
names: [Refactor, Fixed, Feature, Update]
repo_url: https://github.com/gookit/gitw

filters:
  # message length should >= 12
  - name: msgLen
    min_len: 12
  # message words should >= 3
  - name: wordsLen
    min_len: 3
  - name: keywords
    keywords: ['format code']
    exclude: true

# group match rules
# not matched will use 'Other' group.
rules:
  - name: Refactor
    start_withs: [refactor, break]
    contains: ['refactor:']
  - name: Fixed
    start_withs: [fix]
    contains: ['fix:']
  - name: Feature
    start_withs: [feat, new]
    contains: [feature]
  - name: Update
    start_withs: [update, 'up:']
    contains: [' update']
