name: Tag-release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        go: [1.17]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go Faster
        uses: WillAbides/setup-go-faster@v1.7.0
        timeout-minutes: 3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Setup ENV
        # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
        run: |
          echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
          echo "RELEASE_NAME=$GITHUB_WORKFLOW" >> $GITHUB_ENV

      - name: Display Env
        run: |
          env
          git fetch --unshallow
          git pull

      # https://github.com/softprops/action-gh-release
      - name: Create release and upload assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.RELEASE_TAG }}
          tag_name: ${{ env.RELEASE_TAG }}
          body_path: changelog.md
          token: ${{ secrets.GITHUB_TOKEN }}
#          files: macos-chlog.exe
